# Site settings
title: Recipes
email: 
description: The awesome recipe database
start_url: "https://recipes.pintsizedcrafts.com"
baseurl: ""
language: "en"
lang_direction: "ltr"
twitter_username: 
github_username:  netro256

# Template colors used site-wide via css
colors:
  primary-text-color: "#fff"
  secondary-text-color: "#F0EB8D"
  primary-bg-color: "#2D2727"
  tile-color: "#5D3891"
  menu-color: "#413543"

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true
  tips:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

translation:
  en:
    components: "Components"
    ingredients: "Ingredients"
    directions: "Directions"
    category: "Category"
    categories: "Categories"
    nutritional_information: "Nutritional Information"
    component_based: 'This is a <strong class="preffered-color">component-based recipe</strong>.'
    search: "Search"
    blog: "Blog"
    subscribe: "Subscribe"
    home: "Home"
    tips: "Tips"
    notes: "Notes"
    yield: "Servings:"
    preptime: "Prep Time:"
    cooktime: "Cooking Time:"
  de:
    components: "Komponenten"
    ingredients: "Zutaten"
    directions: "Zubereitung"
    category: "Kategorie"
    categories: "Kategories"
    nutritional_information: "Nährwertangaben"
    component_based: 'Dieses Rezept besteht aus <strong class="preffered-color">mehreren Komponenten</strong>.'
    search: "Suche"
    blog: "Blog"
    subscribe: "Abonnieren"
    home: "Home"
    tips: "Tips"
    notes: "Notes"
    yield: "Yield:"
    preptime: "Preparation Time:"
    cooktime: "Cooking Time:"